In [26]:
import pandas as pd
import numpy as np

In [1]:
ticker = 'DOCU'

In [10]:
#Read in earnings data for ticker as df
df = pd.read_csv(f'data/{ticker}_earnings.csv', index_col = 'reportedDate')
df.index = pd.to_datetime(df.index)

In [12]:
df

,surprise,surprisePercentage,reported_Quarterly_EPS,estimated_Quarterly_EPS,reported_Annual_EPS
reportedDate,,,,,
2018-09-05,0.0226,305.4054,0.0300,0.0074,NaN
2018-12-06,-0.2994,-1931.6129,-0.3149,-0.0155,NaN
2019-03-14,0.0548,1053.8462,0.0600,0.0052,NaN
2019-06-06,0.0249,55.2106,0.0700,0.0451,NaN
2019-09-05,-0.0276,-73.4043,0.0100,0.0376,NaN
2019-12-05,0.0731,198.1030,0.1100,0.0369,NaN
2020-03-12,0.0659,121.8115,0.1200,0.0541,0.31
2020-06-04,0.0187,18.4600,0.1200,0.1013,NaN
2020-09-03,0.0922,118.5090,0.1700,0.0778,NaN
2020-12-03,0.0853,63.3259,0.2200,0.1347,0.51

In [13]:
#Read in Additional CANSLIM inputs from Finviz notebook as df1
df1 = pd.read_csv(f'data/{ticker}_CANSLIM_data.csv', index_col = 'date')
df1.index = pd.to_datetime(df1.index)

In [15]:
df1

,IWO_5d_EMA,IWO_10d_EMA,IWO_150d_EMA,Institutional_Ownership,Change_Instituional_Ownership_3months,ROE_TTM
date,,,,,,
2021-01-21,311.061,307.0653,248.0636,0.753,0.0009,-0.4385

In [20]:
#Merge dataframes on datetime index
merge = pd.merge(df, df1, how ='outer',left_index = True, right_index = True)

In [21]:
merge

,surprise,surprisePercentage,reported_Quarterly_EPS,estimated_Quarterly_EPS,reported_Annual_EPS,IWO_5d_EMA,IWO_10d_EMA,IWO_150d_EMA,Institutional_Ownership,Change_Instituional_Ownership_3months,ROE_TTM
2018-09-05,0.0226,305.4054,0.0300,0.0074,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-12-06,-0.2994,-1931.6129,-0.3149,-0.0155,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-03-14,0.0548,1053.8462,0.0600,0.0052,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-06-06,0.0249,55.2106,0.0700,0.0451,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-09-05,-0.0276,-73.4043,0.0100,0.0376,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-12-05,0.0731,198.1030,0.1100,0.0369,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-03-12,0.0659,121.8115,0.1200,0.0541,0.31,NaN,NaN,NaN,NaN,NaN,NaN
2020-06-04,0.0187,18.4600,0.1200,0.1013,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-09-03,0.0922,118.5090,0.1700,0.0778,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-12-03,0.0853,63.3259,0.2200,0.1347,0.51,NaN,NaN,NaN,NaN,NaN,NaN
2021-01-21,NaN,NaN,NaN,NaN,NaN,311.061,307.0653,248.0636,0.753,0.0009,-0.4385

In [32]:
#Build fuction to output which CANSLIM criteria are met for ticker

def canslim(df):
    annual_earnings = []
    quarterly_earnings = []
    cols = ['reported_Quarterly_EPS', 'reported_Annual_EPS']
    for i in df['reported_Quarterly_EPS']:
        if np.isnan(i) == False:
            quarterly_earnings.append(i)
    for i in df['reported_Annual_EPS']:
        if np.isnan(i) == False:
            annual_earnings.append(i)

In [33]:
canslim(merge)

[0.31, 0.51]